(()=>{'use strict';
const BANK={
'Communication':[['💬 TEXT — SAY IT CLEARER','Pick one answer where your styles differed. Each person explains what they actually need in that situation in one sentence.'],['🎙️ VOICE — HEAR ME OUT','Send a short voice note answering: “What helps you feel understood when something matters?” Then compare.']],
'Emotional Connection':[['💭 REVEAL — LITTLE THING, BIG DEAL','Each name one small thing the other person could do that would make you feel more emotionally connected.'],['🎙️ VOICE — FEELING SEEN','Finish this in a voice note: “I feel closest to someone when they…” Then trade answers.']],
'Quality Time':[['📅 PICK ONE — YOUR KIND OF TIME','Each choose one: planned date, spontaneous adventure, stay-in night, errands together, or long conversation. Find the overlap and make it your next hangout.'],['📸 PHOTO — SAVE THIS SPOT','Send a photo of somewhere you would genuinely enjoy spending uninterrupted time together. No explanation until they react.']],
'Chemistry':[['😏 TEXT — WHAT I NOTICE','Tell each other one non-explicit thing that creates chemistry for you: eye contact, humor, confidence, closeness, teasing, conversation, or something else.'],['🎵 MUSIC — VIBE IN A SONG','Send one song that captures the energy between you right now. Explain the choice only after both songs are sent.']],
'Relationship Expectations':[['👀 REAL TALK — DEFINE THE VIBE','Each finish: “If this connection became closer, I would want…” Compare answers without trying to persuade each other.'],['🧭 CHECK-IN — MORE / SAME / LESS','Separately choose whether you want more closeness, roughly the same vibe, or more space. Reveal together, then talk about what that means.']]
};
const clean=s=>s.trim();
function apply(){const root=document.getElementById('results');if(!root||root.classList.contains('hidden'))return;const box=document.getElementById('conversationStarters');if(!box||box.dataset.nextMove==='1')return;const scores=[...document.querySelectorAll('#scoreGrid .score')].map(el=>{const strong=el.querySelector('strong');return{name:clean(el.childNodes[0]?.textContent||''),score:parseInt(strong?.textContent)||0}}).filter(x=>BANK[x.name]);if(scores.length<3)return;const low=[...scores].sort((a,b)=>a.score-b.score).slice(0,3),pool=[];low.forEach(x=>BANK[x.name].forEach(c=>pool.push([x.name,...c])));const used=new Set(),out=[];for(const x of pool){const media=x[1].split(' — ')[0];if(!used.has(media)){out.push(x);used.add(media)}if(out.length===3)break}for(const x of pool){if(out.length===3)break;if(!out.includes(x))out.push(x)}box.dataset.nextMove='1';const card=box.closest('.card');if(card){const pill=card.querySelector('.pill'),h=card.querySelector('h2');if(pill)pill.textContent='Your next move';if(h)h.textContent='Try This Next 👀'}box.innerHTML='<p class="sub">Built around the parts of your vibe with the most room to understand each other better: <strong>'+low.map(x=>x.name+' '+x.score+'%').join(' • ')+'</strong></p>'+out.map(x=>'<div class="starter"><strong>'+x[1]+'</strong><br>'+x[2]+'</div>').join('')+'<div class="tiny" style="margin-top:12px">These are conversation prompts, not compatibility prescriptions. Either person can skip one.</div>';
}
new MutationObserver(apply).observe(document.getElementById('results'),{attributes:true,subtree:true,childList:true});apply();
})();