(()=>{'use strict';if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));let d=null;addEventListener('beforeinstallprompt',e=>{e.preventDefault();d=e;install()});function install(){if(document.querySelector('.pwa-install')||matchMedia('(display-mode: standalone)').matches)return;const b=document.createElement('button');b.className='btn primary pwa-install';b.textContent='Add Vibe Check to Home Screen';b.style.cssText='position:fixed;right:12px;bottom:calc(12px + env(safe-area-inset-bottom));z-index:70;width:auto;max-width:calc(100vw - 24px)';b.onclick=async()=>{if(d){d.prompt();await d.userChoice;d=null;b.remove()}else alert('On iPhone: tap Share, then Add to Home Screen.')};document.body.appendChild(b)}function net(){let x=document.querySelector('.net-note');if(!navigator.onLine&&!x){x=document.createElement('div');x.className='net-note';x.textContent='Offline — you can reopen the app shell, but invitations and reveals need internet.';x.style.cssText='position:fixed;top:0;left:0;right:0;z-index:99;padding:8px;text-align:center;background:#261b31;color:#fff;font:700 12px system-ui';document.body.appendChild(x)}if(navigator.onLine&&x)x.remove()}addEventListener('online',net);addEventListener('offline',net);net();if(/iphone|ipad|ipod/i.test(navigator.userAgent)&&!navigator.standalone)setTimeout(install,1800)})();

/* Shared test UX: NO WARNING mechanics, Vibe Check personality. */
(()=>{'use strict';const s=document.createElement('style');s.id='nw-question-ux';s.textContent=`
#quiz{min-height:calc(100vh - 110px);display:flex;align-items:center}
#quiz>.card{width:100%;margin:0;padding:24px;border-radius:26px;background:rgba(23,21,31,.94);border:1px solid rgba(255,255,255,.10);box-shadow:0 30px 90px rgba(0,0,0,.38)}
#quiz .meta{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);font-weight:850}
#quiz .progress{height:7px;margin:7px 0 20px;background:rgba(255,255,255,.07)}
#quiz .pill{padding:0;border:0;background:transparent;border-radius:0;color:#dfc6f3;font-size:12px;font-weight:900;letter-spacing:.18em;text-transform:uppercase}
#quiz .qtitle{font-size:clamp(27px,7vw,42px);line-height:1.05;letter-spacing:-.04em;margin:12px 0 22px;font-weight:900}
#quiz .options{gap:10px}
#quiz .option{min-height:0;padding:16px;border-radius:16px;background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.10);line-height:1.35;font-weight:700;transition:transform .12s,border-color .12s,background .12s}
#quiz .option:active{transform:scale(.985)}
#quiz .option.selected{border-color:#b66cff;background:linear-gradient(100deg,rgba(166,108,255,.24),rgba(255,95,162,.12));box-shadow:0 0 0 1px rgba(182,108,255,.12)}
#quiz .badge{display:none}
#quiz textarea{min-height:132px;font-size:17px;line-height:1.45}
#quiz>.card>.row{margin-top:18px!important;display:grid;grid-template-columns:minmax(90px,.36fr) minmax(0,1fr);gap:10px}
#quiz .btn{width:100%;min-height:54px;border-radius:17px;font-weight:900;letter-spacing:.07em;text-transform:uppercase}
#quiz #backBtn{order:0;background:transparent;border:1px solid rgba(255,255,255,.10);color:var(--muted)}
#quiz #nextBtn{order:1;background:linear-gradient(135deg,#9d55f5,#e44f9a);box-shadow:0 0 30px rgba(166,108,255,.16)}
#quiz #backBtn:disabled{opacity:.28}
@media(max-width:560px){.wrap{padding-left:16px;padding-right:16px}#quiz{min-height:calc(100svh - 90px)}#quiz>.card{padding:20px}#quiz>.card>.row{grid-template-columns:100px 1fr}.pwa-install{display:none!important}}
`;document.head.appendChild(s);
function syncQuiz(){const quiz=document.getElementById('quiz');if(!quiz||quiz.classList.contains('hidden'))return;const n=document.getElementById('nextBtn'),b=document.getElementById('backBtn'),count=document.getElementById('qCount');if(b)b.textContent='← BACK';if(n){const last=count&&/^27\s*\/\s*27$/.test(count.textContent.trim());n.textContent=last?'LOCK IT IN':'OWN IT →'}const pill=quiz.querySelector('#questionWrap .pill');if(pill)pill.setAttribute('aria-label','Question section')}
const mo=new MutationObserver(syncQuiz);mo.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class']});syncQuiz();})();

(()=>{if(!new URLSearchParams(location.search).has('qa'))return;const p=document.createElement('div');p.style.cssText='position:fixed;left:10px;bottom:10px;z-index:120;background:#111e;color:white;border:1px solid #777;border-radius:14px;padding:10px;font:12px system-ui;max-width:260px';p.innerHTML='<b>Vibe PWA QA</b><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:8px"><button data-pqa="resume">Interrupted Resume</button><button data-pqa="offline">Offline Banner</button><button data-pqa="invalid">Invalid/Expired Link</button><button data-pqa="clear">Clear Saved State</button></div><div style="margin-top:6px;opacity:.75">Display: '+(matchMedia('(display-mode: standalone)').matches?'standalone':'browser')+'</div>';document.body.appendChild(p);p.onclick=e=>{const a=e.target.dataset.pqa;if(!a)return;if(a==='resume'){const x="{\"state\":{\"mode\":\"first\",\"partner\":null,\"me\":{\"nickname\":\"QA Resume\"},\"idx\":9,\"answers\":[1,2,3,4,5,6,7,8,9,1]},\"href\":\"\",\"ts\":0}";const o=JSON.parse(x);o.ts=Date.now();if(o.href!==undefined)o.href=location.href;localStorage.setItem('vibe_progress_v2',JSON.stringify(o));location.href=location.pathname+'?qa=1'}else if(a==='offline'){window.dispatchEvent(new Event('offline'))}else if(a==='invalid'){location.href=location.pathname+'#vibe-reveal-session=deadbeef'}else if(a==='clear'){localStorage.removeItem('vibe_progress_v2');location.reload()}}})();